fuck ittttttttttttttttt just chmod 777 the virtualenv UGH WILDERRRRRR

diff --git a/tt-metal/Dockerfile.tg b/tt-metal/Dockerfile.tg
--- a/tt-metal/Dockerfile.tg
+++ b/tt-metal/Dockerfile.tg
@@ -12,13 +12,17 @@ LABEL org.opencontainers.image.licenses=MIT
 RUN apt update && apt install git git-lfs -y --no-install-recommends
 
 # Have to install python packages as root because the venv is owned by root
-RUN python3 -m pip install pytest-repeat
+RUN [ -n "$VIRTUAL_ENV" ] || { echo "Error: VIRTUAL_ENV env var does not exist. Please check tt-metal release Dockerfile"; exit 1; }
+RUN chmod -R 777 $VIRTUAL_ENV
 
 ## add user
 RUN adduser --uid 1000 --shell /bin/bash user
 USER user
 
 RUN git clone https://github.com/tenstorrent/tt-metal --branch $TT_METAL_VERSION /home/user/tt-metal
+
+RUN python3 -m pip install pytest-repeat
+RUN python3 -m pip install -r tt_metal/python_env/requirements-dev.txt
 
 WORKDIR /home/user/tt-metal
 
